### ISSUE TITLE
Documentation in Dawn

### ISSUE THREAD

**Issue by AllanYangZhou** [pioneers/daemon#139]
We want a button in Dawn that opens up the student API documentation. This should be in the editor toolbar.

**Comment by kevinmasd** [comment]
Is this even possible if the robot is disconnected from the internet, unless we keep a cached version?

Or is this general use, which is limited given everybody checks the website to reinstall Dawn anyway.

**Comment by AllanYangZhou** [comment]
Yeah, it would probably be an offline version of the documentation, not online. We probably won't be adding this feature this year, maybe next year.
