### ISSUE TITLE
Peripheral renaming doesn't work the second time

### ISSUE THREAD

**Issue by AllanYangZhou** [pioneers/daemon#240]
To reproduce:
1. Rename a peripheral.
2. Click to rename the peripheral again. You will still see the old name. You have to refresh/reload Dawn in order to make things work again.

**Comment by kevinmasd** [comment]
The new system broken the name validation. Quick fix is https://github.com/kevinmasd/daemon/blob/develop/dawn/js/components/NameEdit.js but it strictly speaking violates abstraction.

**Comment by AllanYangZhou** [comment]
Fixed by #241 and #242
